Repository chaoss/wg-evolution, pull requests merged in 2019-01, with the labels that each got.

#68 Update Risk Focus Area
  focus_areas/risk.md
Labels: focus area

#63 [use_cases] First try at adding metrics to a use case
  use_cases/first-code-contributions.md
Labels: use case

#58 Suggesting a structural change in README file
  README.md
Labels: enhancement

#70 Advancing with the restructuring of the README.md file
  README.md
Labels: enhancement

#74 First version of a roadmap
  ROADMAP.md
Labels: enhancement

#72 Starting a proposal for Code Changes.
  focus_areas/Code_Changes.md
  focus_areas/code_development.md
Labels: enhancement, metric
